QualOutdoor Recorder: com.qualoutdoor.recorder.QualOutdoorApp Class Reference
com.qualoutdoor.recorder.QualOutdoorApp Class Reference
Classes
interface NetworkChangeListener
Public Member Functions
QualOutdoorApp ()
int getCurrentNetwork ()
void setCurrentNetwork (int network)
int getCallState ()
void setCallState (int callState)
void addNetworkChangeListener (NetworkChangeListener l)
void removeNetworkChangeListener (NetworkChangeListener l)
void notifyNetworkListeners (int currentNetwork, int currentCallState)
boolean isRecording ()
void switchRecording ()
void notifyRecording ()
Private Member Functions
void stopRecording ()
void startRecording ()
Private Attributes
final CopyOnWriteArrayList
< NetworkChangeListener > networkListeners
int currentNetwork = TelephonyManager.NETWORK_TYPE_UNKNOWN
int callState = TelephonyManager.CALL_STATE_IDLE
boolean recording = false
Detailed Description
The application class, it holds attributes and methods that are global to the application
Definition at line 14 of file QualOutdoorApp.java.
Constructor & Destructor Documentation
com.qualoutdoor.recorder.QualOutdoorApp.QualOutdoorApp ()
The application constructor
Definition at line 36 of file QualOutdoorApp.java.
Member Function Documentation
void com.qualoutdoor.recorder.QualOutdoorApp.addNetworkChangeListener (NetworkChangeListener l)
Add a new listener
Definition at line 65 of file QualOutdoorApp.java.
int com.qualoutdoor.recorder.QualOutdoorApp.getCallState ()
Get the current call state
Definition at line 54 of file QualOutdoorApp.java.
int com.qualoutdoor.recorder.QualOutdoorApp.getCurrentNetwork ()
Get the current network value
Definition at line 41 of file QualOutdoorApp.java.
boolean com.qualoutdoor.recorder.QualOutdoorApp.isRecording ()
Indicate if the background recording process is running
Definition at line 84 of file QualOutdoorApp.java.
void com.qualoutdoor.recorder.QualOutdoorApp.notifyNetworkListeners (int currentNetwork, int currentCallState)
Notifies the network changes listeners that the network type has changed
Definition at line 75 of file QualOutdoorApp.java.
References com.qualoutdoor.recorder.QualOutdoorApp.networkListeners.
Referenced by com.qualoutdoor.recorder.QualOutdoorApp.setCallState(), and com.qualoutdoor.recorder.QualOutdoorApp.setCurrentNetwork().
void com.qualoutdoor.recorder.QualOutdoorApp.notifyRecording ()
Create a notification according to the recorder state
Definition at line 112 of file QualOutdoorApp.java.
Referenced by com.qualoutdoor.recorder.QualOutdoorApp.startRecording(), and com.qualoutdoor.recorder.QualOutdoorApp.stopRecording().
void com.qualoutdoor.recorder.QualOutdoorApp.removeNetworkChangeListener (NetworkChangeListener l)
Remove a listener to the list
Definition at line 70 of file QualOutdoorApp.java.
void com.qualoutdoor.recorder.QualOutdoorApp.setCallState (int callState)
Modify the current call state
Definition at line 59 of file QualOutdoorApp.java.
References com.qualoutdoor.recorder.QualOutdoorApp.notifyNetworkListeners().
void com.qualoutdoor.recorder.QualOutdoorApp.setCurrentNetwork (int network)
Modify the current network value
Definition at line 46 of file QualOutdoorApp.java.
References com.qualoutdoor.recorder.QualOutdoorApp.notifyNetworkListeners().
void com.qualoutdoor.recorder.QualOutdoorApp.startRecording () private
Start the recording
Definition at line 105 of file QualOutdoorApp.java.
References com.qualoutdoor.recorder.QualOutdoorApp.notifyRecording().
Referenced by com.qualoutdoor.recorder.QualOutdoorApp.switchRecording().
void com.qualoutdoor.recorder.QualOutdoorApp.stopRecording () private
Stop the recording
Definition at line 98 of file QualOutdoorApp.java.
References com.qualoutdoor.recorder.QualOutdoorApp.notifyRecording().
Referenced by com.qualoutdoor.recorder.QualOutdoorApp.switchRecording().
void com.qualoutdoor.recorder.QualOutdoorApp.switchRecording ()
Start or stop the recording
Definition at line 89 of file QualOutdoorApp.java.
References com.qualoutdoor.recorder.QualOutdoorApp.startRecording(), and com.qualoutdoor.recorder.QualOutdoorApp.stopRecording().
Member Data Documentation
final CopyOnWriteArrayList<NetworkChangeListener> com.qualoutdoor.recorder.QualOutdoorApp.networkListeners private
The registered network changes listeners
Definition at line 24 of file QualOutdoorApp.java.
Referenced by com.qualoutdoor.recorder.QualOutdoorApp.notifyNetworkListeners().
The documentation for this class was generated from the following file:
src/com/qualoutdoor/recorder/QualOutdoorApp.java