QualOutdoor Recorder: com.qualoutdoor.recorder.recording.RecordingHandler Class Reference
com.qualoutdoor.recorder.recording.RecordingHandler Class Reference
Classes
class InsertSampleTask
class WritingCallbackPreferences
Public Member Functions
RecordingHandler (RecordingService recordingService, int sampleRate)
void handleMessage (Message msg)
boolean isRecording ()
void register (IRecordingListener listener)
void unregister (IRecordingListener listener)
void setSamplingRate (int millis)
void addFileToArchive (String fileName, ByteArrayOutputStream fileContent) throws IOException
Static Public Attributes
static final int MESSAGE_START_RECORD = 101
static final int MESSAGE_STOP_RECORD = 102
static final int MESSAGE_UPLOAD_DATABASE = 103
Private Member Functions
void actionStartRecord ()
void actionStopRecord ()
void actionUploadDatabase (int chosenProtocol)
void actionSample ()
void checkCloseDatabase ()
void onFinishRecording ()
void setNotifyRecording (boolean state)
Private Attributes
RecordingService recordingService
ArrayList< IRecordingListener > recordingListeners = new ArrayList<IRecordingListener>()
boolean isRecording = false
int sampleTaskCount = 0
int uploadTaskCount = 0
int sampleRate
boolean shouldClose = true
SQLConnector connector
Static Private Attributes
static final int MESSAGE_SAMPLE = 104
Detailed Description
This Handler is used to manage AsyncTask related to the database by sending messages. The possible actions are starting or stopping a record and requesting an upload of the local database.
Author
Gaborit Nicolas
Definition at line 38 of file RecordingHandler.java.
Constructor & Destructor Documentation
com.qualoutdoor.recorder.recording.RecordingHandler.RecordingHandler (RecordingService recordingService, int sampleRate)
Create a new RecordingHandler with the given sampleRate
Parameters
recordingService The service using this handler
sampleRate The initial value of the sample rate
Definition at line 92 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.recordingService, and com.qualoutdoor.recorder.recording.RecordingHandler.sampleRate.
Member Function Documentation
void com.qualoutdoor.recorder.recording.RecordingHandler.actionSample () private
Action performed when a MESSAGE_SAMPLE is received
Definition at line 191 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_SAMPLE, and com.qualoutdoor.recorder.recording.RecordingHandler.sampleRate.
void com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord () private
Action performed when a MESSAGE_START_RECORD is received. Might fail due to connector failing to open.
Definition at line 124 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.connector, com.qualoutdoor.recorder.persistent.SQLConnector.isOpen, com.qualoutdoor.recorder.recording.RecordingHandler.isRecording(), com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_SAMPLE, com.qualoutdoor.recorder.recording.RecordingHandler.recordingService, com.qualoutdoor.recorder.recording.RecordingHandler.setNotifyRecording(), and com.qualoutdoor.recorder.recording.RecordingHandler.shouldClose.
void com.qualoutdoor.recorder.recording.RecordingHandler.actionStopRecord () private
Action performed when a MESSAGE_STOP_RECORD is received.
Definition at line 150 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.isRecording(), com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_SAMPLE, com.qualoutdoor.recorder.recording.RecordingHandler.onFinishRecording(), com.qualoutdoor.recorder.recording.RecordingHandler.setNotifyRecording(), and com.qualoutdoor.recorder.recording.RecordingHandler.shouldClose.
void com.qualoutdoor.recorder.recording.RecordingHandler.actionUploadDatabase (int chosenProtocol) private
Action performed when a MESSAGE_UPLOAD_DATABASE is received. Convert the whole database to a custom CSV file and try to upload this file with the chosen protocol
Parameters
chosenProtocol The protocol used for the upload
Definition at line 172 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.connector, com.qualoutdoor.recorder.persistent.SQLConnector.isOpen, and com.qualoutdoor.recorder.recording.RecordingHandler.uploadTaskCount.
void com.qualoutdoor.recorder.recording.RecordingHandler.addFileToArchive (String fileName, ByteArrayOutputStream fileContent) throws IOException
Add file into the archive destined for the pending uploads
Parameters
fileName The name of the file to add
fileContent The content of the file to add
Exceptions
IOException
Definition at line 447 of file RecordingHandler.java.
References com.qualoutdoor.recorder.QualOutdoorRecorderApp.ARCHIVE_NAME, and com.qualoutdoor.recorder.recording.RecordingHandler.recordingService.
void com.qualoutdoor.recorder.recording.RecordingHandler.checkCloseDatabase () private
Check that no task will use the database in the future and close it if needed
Definition at line 207 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.connector, com.qualoutdoor.recorder.persistent.SQLConnector.isOpen, com.qualoutdoor.recorder.recording.RecordingHandler.sampleTaskCount, com.qualoutdoor.recorder.recording.RecordingHandler.shouldClose, and com.qualoutdoor.recorder.recording.RecordingHandler.uploadTaskCount.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.onFinishRecording().
boolean com.qualoutdoor.recorder.recording.RecordingHandler.isRecording ()
Indicate if a recording process is in progress
Definition at line 235 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord(), com.qualoutdoor.recorder.recording.RecordingHandler.actionStopRecord(), com.qualoutdoor.recorder.recording.RecordingHandler.register(), and com.qualoutdoor.recorder.recording.RecordingHandler.setNotifyRecording().
void com.qualoutdoor.recorder.recording.RecordingHandler.onFinishRecording () private
Called when the recording process is finished and all the sampling tasks are done
Definition at line 221 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.checkCloseDatabase(), and com.qualoutdoor.recorder.recording.RecordingHandler.sampleTaskCount.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionStopRecord().
void com.qualoutdoor.recorder.recording.RecordingHandler.register (IRecordingListener listener)
Add a recording listener
Parameters
listener The listener to register
Definition at line 245 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.isRecording().
void com.qualoutdoor.recorder.recording.RecordingHandler.setNotifyRecording (boolean state) private
Change and notify that the recording process state has changed
Parameters
state The new recording state
Definition at line 269 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.isRecording(), and com.qualoutdoor.recorder.recording.RecordingHandler.recordingListeners.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord(), and com.qualoutdoor.recorder.recording.RecordingHandler.actionStopRecord().
void com.qualoutdoor.recorder.recording.RecordingHandler.setSamplingRate (int millis)
Modify the sampling rate of the recording.
Parameters
millis The number of milliseconds between each sample
Definition at line 285 of file RecordingHandler.java.
References com.qualoutdoor.recorder.recording.RecordingHandler.sampleRate.
void com.qualoutdoor.recorder.recording.RecordingHandler.unregister (IRecordingListener listener)
Remove a recording listener
Parameters
listener The listener to remove
Definition at line 258 of file RecordingHandler.java.
Member Data Documentation
SQLConnector com.qualoutdoor.recorder.recording.RecordingHandler.connector private
The SQLConnector used for all the database operations
Definition at line 82 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord(), com.qualoutdoor.recorder.recording.RecordingHandler.actionUploadDatabase(), and com.qualoutdoor.recorder.recording.RecordingHandler.checkCloseDatabase().
boolean com.qualoutdoor.recorder.recording.RecordingHandler.isRecording = false private
Indicate if the handler is currently recording
Definition at line 65 of file RecordingHandler.java.
final int com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_SAMPLE = 104 static private
Message code for a sample action (used only internally)
Definition at line 57 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionSample(), com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord(), and com.qualoutdoor.recorder.recording.RecordingHandler.actionStopRecord().
final int com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_START_RECORD = 101 static
Message code for starting recording
Definition at line 41 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingService.onStartCommand().
final int com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_STOP_RECORD = 102 static
Message code for stopping recording
Definition at line 43 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingService.stopRecording().
final int com.qualoutdoor.recorder.recording.RecordingHandler.MESSAGE_UPLOAD_DATABASE = 103 static
Message code for initiating a conversion and upload of the database. This message should always be sent along with the chosen protocol code as arg1. Example :
Message msg = recordingHandler.obtainMessage(
         RecordingHandler.MESSAGE_UPLOAD_DATABASE, chosenProtocol, 0);
recordingHandler.sendMessage(msg);
Definition at line 55 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingService.uploadDatabase().
ArrayList<IRecordingListener> com.qualoutdoor.recorder.recording.RecordingHandler.recordingListeners = new ArrayList<IRecordingListener>() private
The listeners to the recording state
Definition at line 63 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.setNotifyRecording().
RecordingService com.qualoutdoor.recorder.recording.RecordingHandler.recordingService private
The recording service using this handler
Definition at line 60 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord(), com.qualoutdoor.recorder.recording.RecordingHandler.addFileToArchive(), and com.qualoutdoor.recorder.recording.RecordingHandler.RecordingHandler().
int com.qualoutdoor.recorder.recording.RecordingHandler.sampleRate private
The delay between samples
Definition at line 74 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionSample(), com.qualoutdoor.recorder.recording.RecordingHandler.RecordingHandler(), and com.qualoutdoor.recorder.recording.RecordingHandler.setSamplingRate().
int com.qualoutdoor.recorder.recording.RecordingHandler.sampleTaskCount = 0 private
The number of ongoing sample task
Definition at line 68 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.checkCloseDatabase(), and com.qualoutdoor.recorder.recording.RecordingHandler.onFinishRecording().
boolean com.qualoutdoor.recorder.recording.RecordingHandler.shouldClose = true private
Indicate if the tasks should close the database when done
Definition at line 79 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionStartRecord(), com.qualoutdoor.recorder.recording.RecordingHandler.actionStopRecord(), and com.qualoutdoor.recorder.recording.RecordingHandler.checkCloseDatabase().
int com.qualoutdoor.recorder.recording.RecordingHandler.uploadTaskCount = 0 private
The number of ongoing upload database task
Definition at line 71 of file RecordingHandler.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingHandler.actionUploadDatabase(), and com.qualoutdoor.recorder.recording.RecordingHandler.checkCloseDatabase().
The documentation for this class was generated from the following file:
src/com/qualoutdoor/recorder/recording/RecordingHandler.java