QualOutdoor Recorder: com.qualoutdoor.recorder.telephony.ViewCellInfo Class Reference
com.qualoutdoor.recorder.telephony.ViewCellInfo Class Reference
Public Member Functions
ViewCellInfo (Context context)
ViewCellInfo (Context context, AttributeSet attrs)
ViewCellInfo (Context context, AttributeSet attrs, int defStyle)
void updateCellInfo (ICellInfo newCellInfo)
Static Public Attributes
static final int COLUMN_COUNT = 4
static final int ROW_COUNT = 3
Private Member Functions
String stringify (int value)
String stringify (int value, String unit)
Private Attributes
final CharSequence[] radioNames
ICellInfo cellInfo
TextView viewCidType
TextView viewRSSI
TextView viewMCCvalue
TextView viewMNCvalue
TextView viewLACTAC
TextView viewLACTACvalue
TextView viewPSCPCI
TextView viewPSCPCIvalue
Detailed Description
This view allows to display dynamically, as a table, the infos of an ICellInfo.
Author
Gaborit Nicolas
Definition at line 19 of file ViewCellInfo.java.
Member Function Documentation
String com.qualoutdoor.recorder.telephony.ViewCellInfo.stringify (int value) private
Return a string representing the given value, or the cell_info_empty string if unknown (Integer.MAX_VALUE)
Definition at line 180 of file ViewCellInfo.java.
Referenced by com.qualoutdoor.recorder.telephony.ViewCellInfo.updateCellInfo().
String com.qualoutdoor.recorder.telephony.ViewCellInfo.stringify (int value, String unit) private
Return a string representing the given value with the given unit string, or the cell_info_empty string if unknown (Integer.MAX_VALUE)
Definition at line 192 of file ViewCellInfo.java.
void com.qualoutdoor.recorder.telephony.ViewCellInfo.updateCellInfo (ICellInfo newCellInfo)
Set the CellInfo displayed
Definition at line 100 of file ViewCellInfo.java.
References com.qualoutdoor.recorder.telephony.ICellInfo.getCid(), com.qualoutdoor.recorder.telephony.ICellInfo.getLac(), com.qualoutdoor.recorder.telephony.ICellInfo.getMcc(), com.qualoutdoor.recorder.telephony.ICellInfo.getMnc(), com.qualoutdoor.recorder.telephony.ICellInfo.getPci(), com.qualoutdoor.recorder.telephony.ICellInfo.getPsc(), com.qualoutdoor.recorder.telephony.ICellInfo.getSignalStrength(), com.qualoutdoor.recorder.telephony.ICellInfo.getTac(), com.qualoutdoor.recorder.telephony.ICellInfo.isRegistered(), com.qualoutdoor.recorder.telephony.ViewCellInfo.radioNames, and com.qualoutdoor.recorder.telephony.ViewCellInfo.stringify().
Member Data Documentation
ICellInfo com.qualoutdoor.recorder.telephony.ViewCellInfo.cellInfo private
The displayed ICellInfo
Definition at line 32 of file ViewCellInfo.java.
final int com.qualoutdoor.recorder.telephony.ViewCellInfo.COLUMN_COUNT = 4 static
The number of column of this GridLayout
Definition at line 22 of file ViewCellInfo.java.
final CharSequence [] com.qualoutdoor.recorder.telephony.ViewCellInfo.radioNames private
Initial value:
= getResources().getStringArray(
            R.array.radio_type_name)
The string ressource for the radio types
Definition at line 28 of file ViewCellInfo.java.
Referenced by com.qualoutdoor.recorder.telephony.ViewCellInfo.updateCellInfo().
final int com.qualoutdoor.recorder.telephony.ViewCellInfo.ROW_COUNT = 3 static
The number of rows in this GridLayout
Definition at line 25 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewCidType private
The CID and Type view
Definition at line 35 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewLACTAC private
The LAC or TAC view depending on the type of the cell
Definition at line 47 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewLACTACvalue private
The LAC or TAC value view
Definition at line 50 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewMCCvalue private
The MCC value view
Definition at line 41 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewMNCvalue private
The MNC value view
Definition at line 44 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewPSCPCI private
The PSC or PCI view depending on the type of the cell
Definition at line 53 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewPSCPCIvalue private
The PSC or PCI value view
Definition at line 56 of file ViewCellInfo.java.
TextView com.qualoutdoor.recorder.telephony.ViewCellInfo.viewRSSI private
The RSSI view
Definition at line 38 of file ViewCellInfo.java.
The documentation for this class was generated from the following file:
src/com/qualoutdoor/recorder/telephony/ViewCellInfo.java