QualOutdoor Recorder: com.qualoutdoor.recorder.recording.RecordingService Class Reference
com.qualoutdoor.recorder.recording.RecordingService Class Reference
Public Member Functions
void onCreate ()
IBinder onBind (Intent intent)
boolean isRecording ()
void setSamplingRate (int millis)
int onStartCommand (Intent intent, int flags, int startId)
void onDestroy ()
void stopRecording ()
Private Member Functions
void startRecording ()
Private Attributes
IBinder mRecordingBinder
boolean isRecording = false
Thread thread
Detailed Description
This service when started will link to the TelephonyService and begin sampling the phone state. One can bind to this service in order to modify the sampling rate. It is needed to call stopService() on it in order to stop the recording process.
Definition at line 17 of file RecordingService.java.
Member Function Documentation
boolean com.qualoutdoor.recorder.recording.RecordingService.isRecording ()
Indicates whether the service is currently recording data
Definition at line 44 of file RecordingService.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingService.startRecording(), and com.qualoutdoor.recorder.recording.RecordingService.stopRecording().
void com.qualoutdoor.recorder.recording.RecordingService.setSamplingRate (int millis)
Set the sampling rate to the specified value in milliseconds
Definition at line 49 of file RecordingService.java.
void com.qualoutdoor.recorder.recording.RecordingService.startRecording () private
Start the recording process.
Definition at line 73 of file RecordingService.java.
References com.qualoutdoor.recorder.notifications.NotificationCenter.BACKGROUND_RECORDING, com.qualoutdoor.recorder.recording.RecordingService.isRecording(), and com.qualoutdoor.recorder.recording.RecordingService.thread.
void com.qualoutdoor.recorder.recording.RecordingService.stopRecording ()
Stop the recording process
Definition at line 102 of file RecordingService.java.
References com.qualoutdoor.recorder.recording.RecordingService.isRecording(), and com.qualoutdoor.recorder.recording.RecordingService.thread.
Member Data Documentation
boolean com.qualoutdoor.recorder.recording.RecordingService.isRecording = false private
Indicates if a recording process is ongoing
Definition at line 22 of file RecordingService.java.
IBinder com.qualoutdoor.recorder.recording.RecordingService.mRecordingBinder private
The interface binder for this service
Definition at line 20 of file RecordingService.java.
Thread com.qualoutdoor.recorder.recording.RecordingService.thread private
A fake recording thread
Definition at line 25 of file RecordingService.java.
Referenced by com.qualoutdoor.recorder.recording.RecordingService.startRecording(), and com.qualoutdoor.recorder.recording.RecordingService.stopRecording().
The documentation for this class was generated from the following file:
src/com/qualoutdoor/recorder/recording/RecordingService.java